import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  wiki: [
    {
      type: 'autogenerated',
      dirName: '.',
    }
  ],
};

export default sidebars;
